var countries = {
  "India": "IN",
  "Nepal": "NP",
  "Bangladesh": "BD",
  "Australia": "AL",
  "America": "AC",
};

var states = {
  "Andaman and Nicobar Islands": "IN",
  "Andhra Pradesh": "IN",
  "Arunachal Pradesh": "IN",
  "Assam": "IN",
  "Bihar": "IN",
  "Chandigarh": "IN",
  "Chhattisgarh": "IN",
  "Dadra & Nagar Haveli and Daman & Diu": "IN",
  "Delhi": "IN",
  "Goa": "IN",
  "Gujarat": "IN",
  "Haryana": "IN",
  "Himachal Pradesh": "IN",
  "Jammu and Kashmir": "IN",
  "Jharkhand": "IN",
  "Karnataka": "IN",
  "Kerala": "IN",
  "Ladakh": "IN",
  "Lakshadweep": "IN",
  "Madhya Pradesh": "IN",
  "Maharashtra": "IN",
  "Manipur": "IN",
  "Meghalaya": "IN",
  "Mizoram": "IN",
  "Nagaland": "IN",
  "Odisha": "IN",
  "Puducherry": "IN",
  "Punjab": "IN",
  "Rajasthan": "IN",
  "Sikkim": "IN",
  "Tamil Nadu": "IN",
  "Telangana": "IN",
  "Tripura": "IN",
  "Uttar Pradesh": "IN",
  "Uttarakhand": "IN",
  "West Bengal": "IN",
  "Janakpur Kshetra": "NP",
  "Karnali Kshetra": "NP",
  "Mahakali Kshetra": "NP",
  "Dhaka": "BD",
  "Rangpur": "BD",
};

var districts = {
  "Alluri Sitharama Raju": "Andhra Pradesh",
  "Anakapalli": "Andhra Pradesh",
  "Anantapur": "Andhra Pradesh",
  "Annamayya": "Andhra Pradesh",
  "Bapatla": "Andhra Pradesh",
  "Chittoor": "Andhra Pradesh",
  "East Godavari": "Andhra Pradesh",
  "Eluru": "Andhra Pradesh",
  "Guntur": "Andhra Pradesh",
  "YSR Kadapa": "Andhra Pradesh",
  "Kakinada": "Andhra Pradesh",
  "Krishna": "Andhra Pradesh",
  "Dr. B.R.Ambedkar Konaseema": "Andhra Pradesh",
  "Kurnool": "Andhra Pradesh",
  "Parvathipuram Manyam": "Andhra Pradesh",
  "Nandyal": "Andhra Pradesh",
  "NTR": "Andhra Pradesh",
  "Palnadu": "Andhra Pradesh",
  "Prakasam": "Andhra Pradesh",
  "Nellore": "Andhra Pradesh",
  "Tirupati": "Andhra Pradesh",
  "Sri Sathya Sai": "Andhra Pradesh",
  "Srikakulam": "Andhra Pradesh",
  "Visakhapatnam": "Andhra Pradesh",
  "Vizianagaram": "Andhra Pradesh",
  "West Godavari": "Andhra Pradesh",
};

var mandals = {
  "Addateegala": "Alluri Sitharama Raju",
  "Ananthagiri": "Alluri Sitharama Raju",
  "Araku Valley": "Alluri Sitharama Raju",
  "Chintapalle": "Alluri Sitharama Raju",
  "Chintur": "Alluri Sitharama Raju",
  "Devipatnam": "Alluri Sitharama Raju",
  "Dumbriguda": "Alluri Sitharama Raju",
  "Etapaka": "Alluri Sitharama Raju",
  "G.Madugula": "Alluri Sitharama Raju",
  "Gangavaram": "Alluri Sitharama Raju",
  "Gudem Kotha Veedhi": "Alluri Sitharama Raju",
  "Hukumpeta": "Alluri Sitharama Raju",
  "Koyyuru": "Alluri Sitharama Raju",
  "Kunavaram": "Alluri Sitharama Raju",
  "Maredumilli": "Alluri Sitharama Raju",
  "Munchingi Puttu": "Alluri Sitharama Raju",
  "Paderu": "Alluri Sitharama Raju",
  "Peda Bayalu": "Alluri Sitharama Raju",
  "Rajavommangi": "Alluri Sitharama Raju",
  "Rampachodavaram": "Alluri Sitharama Raju",
  "Vararamachandrapuram": "Alluri Sitharama Raju",
  "Y. Ramavaram": "Alluri Sitharama Raju",
  "Anakapalle": "Ananthagiri",
  "Atchutapuram": "Ananthagiri",
  "Butchayyapeta": "Ananthagiri",
  "Cheedikada": "Ananthagiri",
  "Chodavaram": "Ananthagiri",
  "Devarapalle": "Ananthagiri",
  "Golugonda": "Ananthagiri",
  "K.Kotapadu": "Ananthagiri",
  "Kasimkota": "Ananthagiri",
  "Kotauratla": "Ananthagiri",
  "Madugula": "Ananthagiri",
  "Makavarapalem": "Ananthagiri",
  "Munagapaka": "Ananthagiri",
  "Nakkapalle": "Ananthagiri",
  "Narsipatnam": "Ananthagiri",
  "Nathavaram": "Ananthagiri",
  "Paravada": "Ananthagiri",
  "Payakaraopeta": "Ananthagiri",
  "Rambilli": "Ananthagiri",
  "Ravikamatham": "Ananthagiri",
  "Rolugunta": "Ananthagiri",
  "S.Rayavaram": "Ananthagiri",
  "Sabbavaram": "Ananthagiri",
  "Yelamanchili": "Ananthagiri",
  "Anantapur": "Anantapur",
  "Atmakur": "Anantapur",
  "Beluguppa": "Anantapur",
  "Bommanahal": "Anantapur",
  "Brahmasamudram": "Anantapur",
  "Bukkaraya Samudram": "Anantapur",
  "D.Hirehal": "Anantapur",
  "Garladinne": "Anantapur",
  "Gooty": "Anantapur",
  "Gummagatta": "Anantapur",
  "Guntakal": "Anantapur",
  "Kalyandurg": "Anantapur",
  "Kambadur": "Anantapur",
  "Kanekal": "Anantapur",
  "Kudair": "Anantapur",
  "Kundurpi": "Anantapur",
  "Narpala": "Anantapur",
  "Pamidi": "Anantapur",
  "Peddapappur": "Anantapur",
  "Peddavadugur": "Anantapur",
  "Putlur": "Anantapur",
  "Raptadu": "Anantapur",
  "Rayadurg": "Anantapur",
  "Settur": "Anantapur",
  "Singanamala": "Anantapur",
  "Tadpatri": "Anantapur",
  "Uravakonda": "Anantapur",
  "Vajrakarur": "Anantapur",
  "Vidapanakal": "Anantapur",
  "Yadiki": "Anantapur",
  "Yellanur": "Anantapur",
  "B.Kothakota": "Annamayya",
  "Chinnamandem": "Annamayya",
  "Chitvel": "Annamayya",
  "Galiveedu": "Annamayya",
  "Gurramkonda": "Annamayya",
  "Kalakada": "Annamayya",
  "Kalikiri": "Annamayya",
  "Kambhamvaripalle": "Annamayya",
  "Koduru": "Annamayya",
  "Kurabalakota": "Annamayya",
  "Lakkireddipalle": "Annamayya",
  "Madanapalle": "Annamayya",
  "Mulakalacheruvu": "Annamayya",
  "Nandalur": "Annamayya",
  "Nimmanapalle": "Annamayya",
  "Obulavaripalle": "Annamayya",
  "Pedda Thippasamudram": "Annamayya",
  "Peddamandyam": "Annamayya",
  "Penagalur": "Annamayya",
  "Pileru": "Annamayya",
  "Pullampeta": "Annamayya",
  "Rajampet": "Annamayya",
  "Ramapuram": "Annamayya",
  "Ramasamudram": "Annamayya",
  "Rayachoti": "Annamayya",
  "Sambepalle": "Annamayya",
  "T Sundupalle": "Annamayya",
  "Thamballapalle": "Annamayya",
  "Valmikipuram": "Annamayya",
  "Veeraballe": "Annamayya",
  "Addanki": "Bapatla",
  "Amruthalur": "Bapatla",
  "Ballikurava": "Bapatla",
  "Bapatla": "Bapatla",
  "Bhattiprolu": "Bapatla",
  "Cherukupalle": "Bapatla",
  "Chinaganjam": "Bapatla",
  "Chirala": "Bapatla",
  "Inkollu": "Bapatla",
  "Janakavarampanguluru": "Bapatla",
  "Karamchedu": "Bapatla",
  "Karlapalem": "Bapatla",
  "Kollur": "Bapatla",
  "Korisapadu": "Bapatla",
  "Martur": "Bapatla",
  "Nagaram": "Bapatla",
  "Nizampatnam": "Bapatla",
  "Parchur": "Bapatla",
  "Pittalavanipalem": "Bapatla",
  "Repalle": "Bapatla",
  "Santhamaguluru": "Bapatla",
  "Tsundur": "Bapatla",
  "Vemuru": "Bapatla",
  "Vetapalem": "Bapatla",
  "Yeddana Pudi": "Bapatla",
  "Baireddipalle": "Chittoor",
  "Bangarupalem": "Chittoor",
  "Chittoor": "Chittoor",
  "Chowdepalle": "Chittoor",
  "Gangadhara Nellore": "Chittoor",
  "Gangavaram ": "Chittoor",
  "Gudipala": "Chittoor",
  "Gudupalle": "Chittoor",
  "Irala": "Chittoor",
  "Karvetinagar": "Chittoor",
  "Kuppam": "Chittoor",
  "Nagari": "Chittoor",
  "Nindra": "Chittoor",
  "Palamaner": "Chittoor",
  "Palasamudram": "Chittoor",
  "Peddapanjani": "Chittoor",
  "Penumuru": "Chittoor",
  "Pulicherla": "Chittoor",
  "Punganur": "Chittoor",
  "Puthalapattu": "Chittoor",
  "Ramakuppam": "Chittoor",
  "Rompicherla": "Chittoor",
  "Santhipuram": "Chittoor",
  "Sodam": "Chittoor",
  "Somala": "Chittoor",
  "Srirangarajapuram": "Chittoor",
  "Thavanampalle": "Chittoor",
  "Vedurukuppam": "Chittoor",
  "Venkatagirikota": "Chittoor",
  "Vijayapuram": "Chittoor",
  "Yadamarri": "Chittoor",
  "Anaparthy": "East Godavari",
  "Biccavolu": "East Godavari",
  "Chagallu": "East Godavari",
  "Devarapalle ": "East Godavari",
  "Gokavaram": "East Godavari",
  "Gopalapuram": "East Godavari",
  "Kadiam": "East Godavari",
  "Korukonda": "East Godavari",
  "Kovvur": "East Godavari",
  "Nallajerla": "East Godavari",
  "Nidadavole": "East Godavari",
  "Peravali": "East Godavari",
  "Rajahmundry (Urban)": "East Godavari",
  "Rajahmundry Rural": "East Godavari",
  "Rajanagaram": "East Godavari",
  "Rangampeta": "East Godavari",
  "Seethanagaram": "East Godavari",
  "Tallapudi": "East Godavari",
  "Undrajavaram": "East Godavari",
  "Agiripalle": "Eluru",
  "Bhimadole": "Eluru",
  "Buttayagudem": "Eluru",
  "Chatrai": "Eluru",
  "Chintalapudi": "Eluru",
  "Denduluru": "Eluru",
  "Dwarakatirumala": "Eluru",
  "Eluru": "Eluru",
  "Ganapavaram": "Eluru",
  "Jangareddigudem": "Eluru",
  "Jeelugu Milli": "Eluru",
  "Kaikalur": "Eluru",
  "Kalidindi": "Eluru",
  "Kamavarapukota": "Eluru",
  "Koyyalagudem": "Eluru",
  "Kukunoor": "Eluru",
  "Lingapalem": "Eluru",
  "Mandavalli": "Eluru",
  "Mudinepalle": "Eluru",
  "Musunuru": "Eluru",
  "Nidamarru": "Eluru",
  "Nuzvid": "Eluru",
  "Pedapadu": "Eluru",
  "Pedavegi": "Eluru",
  "Polavaram": "Eluru",
  "T. Narasapuram": "Eluru",
  "Unguturu": "Eluru",
  "Velairpadu": "Eluru",
  "Chebrolu": "Guntur",
  "Duggirala": "Guntur",
  "Guntur East": "Guntur",
  "Guntur West": "Guntur",
  "Kakumanu": "Guntur",
  "Kollipara": "Guntur",
  "Mangalagiri": "Guntur",
  "Medikonduru": "Guntur",
  "Pedakakani": "Guntur",
  "Pedanandipadu": "Guntur",
  "Phirangipuram": "Guntur",
  "Ponnur": "Guntur",
  "Prathipadu": "Guntur",
  "Tadepalle": "Guntur",
  "Tadikonda": "Guntur",
  "Tenali": "Guntur",
  "Thullur": "Guntur",
  "Vatticherukuru": "Guntur",
  "Gandepalli": "Kakinada",
  "Gollaprolu": "Kakinada",
  "Jaggampeta": "Kakinada",
  "Kajuluru": "Kakinada",
  "Kakinada (Rural)": "Kakinada",
  "Kakinada (Urban)": "Kakinada",
  "Karapa": "Kakinada",
  "Kirlampudi": "Kakinada",
  "Kotananduru": "Kakinada",
  "Kothapalle": "Kakinada",
  "Pedapudi": "Kakinada",
  "Peddapuram": "Kakinada",
  "Pithapuram": "Kakinada",
  "Prathipadu ": "Kakinada",
  "Rowthulapudi": "Kakinada",
  "Samalkota": "Kakinada",
  "Sankhavaram": "Kakinada",
  "Thallarevu": "Kakinada",
  "Thondangi": "Kakinada",
  "Tuni": "Kakinada",
  "Yeleswaram": "Kakinada",
  "Ainavilli": "Dr. B.R.Ambedkar Konaseema",
  "Alamuru": "Dr. B.R.Ambedkar Konaseema",
  "Allavaram": "Dr. B.R.Ambedkar Konaseema",
  "Amalapuram": "Dr. B.R.Ambedkar Konaseema",
  "Ambajipeta": "Dr. B.R.Ambedkar Konaseema",
  "Atreyapuram": "Dr. B.R.Ambedkar Konaseema",
  "I. Polavaram": "Dr. B.R.Ambedkar Konaseema",
  "K.Gangavaram": "Dr. B.R.Ambedkar Konaseema",
  "Kapileswarapuram": "Dr. B.R.Ambedkar Konaseema",
  "Katrenikona": "Dr. B.R.Ambedkar Konaseema",
  "Kothapeta": "Dr. B.R.Ambedkar Konaseema",
  "Malikipuram": "Dr. B.R.Ambedkar Konaseema",
  "Mamidikuduru": "Dr. B.R.Ambedkar Konaseema",
  "Mandapeta": "Dr. B.R.Ambedkar Konaseema",
  "Mummidivaram": "Dr. B.R.Ambedkar Konaseema",
  "P.Gannavaram": "Dr. B.R.Ambedkar Konaseema",
  "Ramachandrapuram": "Dr. B.R.Ambedkar Konaseema",
  "Ravulapalem": "Dr. B.R.Ambedkar Konaseema",
  "Rayavaram": "Dr. B.R.Ambedkar Konaseema",
  "Razole": "Dr. B.R.Ambedkar Konaseema",
  "Sakhinetipalle": "Dr. B.R.Ambedkar Konaseema",
  "Uppalaguptam": "Dr. B.R.Ambedkar Konaseema",
  "Avanigadda": "Krishna",
  "Bantumilli": "Krishna",
  "Bapulapadu": "Krishna",
  "Challapalle": "Krishna",
  "Gannavaram": "Krishna",
  "Ghantasala": "Krishna",
  "Gudivada": "Krishna",
  "Gudlavalleru": "Krishna",
  "Guduru": "Krishna",
  "Kankipadu": "Krishna",
  "Koduru ": "Krishna",
  "Kruthivennu": "Krishna",
  "Machilipatnam": "Krishna",
  "Mopidevi": "Krishna",
  "Movva": "Krishna",
  "Nagayalanka": "Krishna",
  "Nandivada": "Krishna",
  "Pamarru": "Krishna",
  "Pamidimukkala": "Krishna",
  "Pedana": "Krishna",
  "Pedaparupudi": "Krishna",
  "Penamaluru": "Krishna",
  "Thotlavalluru": "Krishna",
  "Unguturu ": "Krishna",
  "Vuyyuru": "Krishna",
  "Adoni": "Kurnool",
  "Alur": "Kurnool",
  "Aspari": "Kurnool",
  "C.Belagal": "Kurnool",
  "Chippagiri": "Kurnool",
  "Devanakonda": "Kurnool",
  "Gonegandla": "Kurnool",
  "Gudur": "Kurnool",
  "Halaharvi": "Kurnool",
  "Holagunda": "Kurnool",
  "Kallur": "Kurnool",
  "Kodumur": "Kurnool",
  "Kosigi": "Kurnool",
  "Kowthalam": "Kurnool",
  "Krishnagiri": "Kurnool",
  "Kurnool": "Kurnool",
  "Maddikera (East)": "Kurnool",
  "Mantralayam": "Kurnool",
  "Nandavaram": "Kurnool",
  "Orvakal": "Kurnool",
  "Pattikonda": "Kurnool",
  "Pedda Kadubur": "Kurnool",
  "Tuggali": "Kurnool",
  "Veldurthi": "Kurnool",
  "Yemmiganur": "Kurnool",
  "A.Konduru": "NTR",
  "Chandarlapadu": "NTR",
  "G.Konduru": "NTR",
  "Gampalagudem": "NTR",
  "Ibrahimpatnam": "NTR",
  "Jaggayyapeta": "NTR",
  "Kanchikacherla": "NTR",
  "Mylavaram": "NTR",
  "Nandigama": "NTR",
  "Penuganchiprolu": "NTR",
  "Reddigudem": "NTR",
  "Tiruvuru": "NTR",
  "Vatsavai": "NTR",
  "Veerullapadu": "NTR",
  "Vijayawada (rural)": "NTR",
  "Vijayawada (urban)": "NTR",
  "Vissannapet": "NTR",
  "Allagadda": "Nandyal",
  "Atmakur ": "Nandyal",
  "Banaganapalle": "Nandyal",
  "Bandi Atmakur": "Nandyal",
  "Bethamcherla": "Nandyal",
  "Chagalamarri": "Nandyal",
  "Dhone": "Nandyal",
  "Dornipadu": "Nandyal",
  "Gadivemula": "Nandyal",
  "Gospadu": "Nandyal",
  "Jupadu Bungalow": "Nandyal",
  "Koilkuntla": "Nandyal",
  "Kolimigundla": "Nandyal",
  "Kothapalle ": "Nandyal",
  "Mahanandi": "Nandyal",
  "Midthur": "Nandyal",
  "Nandikotkur": "Nandyal",
  "Nandyal": "Nandyal",
  "Owk": "Nandyal",
  "Pagidyala": "Nandyal",
  "Pamulapadu": "Nandyal",
  "Panyam": "Nandyal",
  "Peapally": "Nandyal",
  "Rudravaram": "Nandyal",
  "Sanjamala": "Nandyal",
  "Sirvel": "Nandyal",
  "Srisailam": "Nandyal",
  "Uyyalawada": "Nandyal",
  "Velgode": "Nandyal",
  "Amaravathi": "Palnadu",
  "Atchampet": "Palnadu",
  "Bellamkonda": "Palnadu",
  "Bollapalle": "Palnadu",
  "Chilakaluripet": "Palnadu",
  "Dachepalle": "Palnadu",
  "Durgi": "Palnadu",
  "Edlapadu": "Palnadu",
  "Gurazala": "Palnadu",
  "Ipur": "Palnadu",
  "Karempudi": "Palnadu",
  "Krosuru": "Palnadu",
  "Macharla": "Palnadu",
  "Machavaram": "Palnadu",
  "Muppalla": "Palnadu",
  "Nadendla": "Palnadu",
  "Narasaraopet": "Palnadu",
  "Nekarikallu": "Palnadu",
  "Nuzendla": "Palnadu",
  "Pedakurapadu": "Palnadu",
  "Piduguralla": "Palnadu",
  "Rajupalem": "Palnadu",
  "Rentachintala": "Palnadu",
  "Rompicherla ": "Palnadu",
  "Sattenapalle": "Palnadu",
  "Savalyapuram": "Palnadu",
  "Veldurti": "Palnadu",
  "Vinukonda": "Palnadu",
  "Balijipeta": "Parvathipuram Manyam",
  "Bhamini": "Parvathipuram Manyam",
  "Garugubilli": "Parvathipuram Manyam",
  "Gummalakshmipuram": "Parvathipuram Manyam",
  "Jiyyammavalasa": "Parvathipuram Manyam",
  "Komarada": "Parvathipuram Manyam",
  "Kurupam": "Parvathipuram Manyam",
  "Makkuva": "Parvathipuram Manyam",
  "Pachipenta": "Parvathipuram Manyam",
  "Palakonda": "Parvathipuram Manyam",
  "Parvathipuram": "Parvathipuram Manyam",
  "Salur": "Parvathipuram Manyam",
  "Seethampeta": "Parvathipuram Manyam",
  "Seethanagaram ": "Parvathipuram Manyam",
  "Veeraghattam": "Parvathipuram Manyam",
  "Ardhaveedu": "Prakasam",
  "Bestawaripeta": "Prakasam",
  "Chandra Sekhara Puram": "Prakasam",
  "Chimakurthi": "Prakasam",
  "Cumbum": "Prakasam",
  "Darsi": "Prakasam",
  "Donakonda": "Prakasam",
  "Dornala": "Prakasam",
  "Giddalur": "Prakasam",
  "Hanumanthuni Padu": "Prakasam",
  "Kanigiri": "Prakasam",
  "Komarolu": "Prakasam",
  "Konakanamitla": "Prakasam",
  "Kondapi": "Prakasam",
  "Kotha Patnam": "Prakasam",
  "Kurichedu": "Prakasam",
  "Maddipadu": "Prakasam",
  "Markapur": "Prakasam",
  "Marripudi": "Prakasam",
  "Mundlamuru": "Prakasam",
  "Naguluppala Padu": "Prakasam",
  "Ongole": "Prakasam",
  "Pamur": "Prakasam",
  "Peda Araveedu": "Prakasam",
  "Pedacherlo Palle": "Prakasam",
  "Podili": "Prakasam",
  "Ponnaluru": "Prakasam",
  "Pullalacheruvu": "Prakasam",
  "Racherla": "Prakasam",
  "Santhanuthala Padu": "Prakasam",
  "Singarayakonda": "Prakasam",
  "Tangutur": "Prakasam",
  "Tarlupadu": "Prakasam",
  "Thallur": "Prakasam",
  "Tripuranthakam": "Prakasam",
  "Veligandla": "Prakasam",
  "Yerragondapalem": "Prakasam",
  "Zarugumilli": "Prakasam",
  "Allur": "Nellore",
  "Ananthasagaram": "Nellore",
  "Anumasamudrampeta": "Nellore",
  "Atmakuru": "Nellore",
  "Bogolu": "Nellore",
  "Buchireddypalem": "Nellore",
  "Chejerla": "Nellore",
  "Dagadarthi": "Nellore",
  "Duttaluru": "Nellore",
  "Gudluru": "Nellore",
  "Indukurpet": "Nellore",
  "Jaladanki": "Nellore",
  "Kaligiri": "Nellore",
  "Kaluvoya": "Nellore",
  "Kandukur": "Nellore",
  "Kavali": "Nellore",
  "Kodavaluru": "Nellore",
  "Kondapuram": "Nellore",
  "Kovuru": "Nellore",
  "Lingasamudram": "Nellore",
  "Manubolu": "Nellore",
  "Marripadu": "Nellore",
  "Muttukuru": "Nellore",
  "Nellore": "Nellore",
  "Podalakuru": "Nellore",
  "Rapuru": "Nellore",
  "Saidapuramu": "Nellore",
  "Sangam": "Nellore",
  "Sitarampuramu": "Nellore",
  "Thotapalligudur": "Nellore",
  "Udayagiri": "Nellore",
  "Ulavapadu": "Nellore",
  "Varikuntapadu": "Nellore",
  "Venkatachalam": "Nellore",
  "Vidavaluru": "Nellore",
  "Vinjamuru": "Nellore",
  "Voletivaripalem": "Nellore",
  "Agali": "Sri Sathya Sai",
  "Amadagur": "Sri Sathya Sai",
  "Amarapuram": "Sri Sathya Sai",
  "Bathalapalle": "Sri Sathya Sai",
  "Bukkapatnam": "Sri Sathya Sai",
  "Chennekothapalle": "Sri Sathya Sai",
  "Chilamathur": "Sri Sathya Sai",
  "Dharmavaram": "Sri Sathya Sai",
  "Gandlapenta": "Sri Sathya Sai",
  "Gorantla": "Sri Sathya Sai",
  "Gudibanda": "Sri Sathya Sai",
  "Hindupur": "Sri Sathya Sai",
  "Kadiri": "Sri Sathya Sai",
  "Kanaganapalle": "Sri Sathya Sai",
  "Kothacheruvu": "Sri Sathya Sai",
  "Lepakshi": "Sri Sathya Sai",
  "Madakasira": "Sri Sathya Sai",
  "Mudigubba": "Sri Sathya Sai",
  "Nallacheruvu": "Sri Sathya Sai",
  "Nallamada": "Sri Sathya Sai",
  "Nambulipulikunta": "Sri Sathya Sai",
  "Obuladevaracheruvu": "Sri Sathya Sai",
  "Parigi": "Sri Sathya Sai",
  "Penukonda": "Sri Sathya Sai",
  "Puttaparthi": "Sri Sathya Sai",
  "Ramagiri": "Sri Sathya Sai",
  "Roddam": "Sri Sathya Sai",
  "Rolla": "Sri Sathya Sai",
  "Somandepalle": "Sri Sathya Sai",
  "Tadimarri": "Sri Sathya Sai",
  "Talupula": "Sri Sathya Sai",
  "Tanakal": "Sri Sathya Sai",
  "Amadalavalasa": "Srikakulam",
  "Burja": "Srikakulam",
  "Etcherla": "Srikakulam",
  "Ganguvarisigadam": "Srikakulam",
  "Gara": "Srikakulam",
  "Hiramandalam": "Srikakulam",
  "Ichchapuram": "Srikakulam",
  "Jalumuru": "Srikakulam",
  "Kanchili": "Srikakulam",
  "Kaviti": "Srikakulam",
  "Kotabommali": "Srikakulam",
  "Kothuru": "Srikakulam",
  "Lakshminarsupeta": "Srikakulam",
  "Laveru": "Srikakulam",
  "Mandasa": "Srikakulam",
  "Meliaputti": "Srikakulam",
  "Nandigam": "Srikakulam",
  "Narasannapeta": "Srikakulam",
  "Palasa": "Srikakulam",
  "Pathapatnam": "Srikakulam",
  "Polaki": "Srikakulam",
  "Ponduru": "Srikakulam",
  "Ranastalam": "Srikakulam",
  "Santhabommali": "Srikakulam",
  "Saravakota": "Srikakulam",
  "Sarubujjili": "Srikakulam",
  "Sompeta": "Srikakulam",
  "Srikakulam": "Srikakulam",
  "Tekkali": "Srikakulam",
  "Vajrapukothuru": "Srikakulam",
  "Balayapalli": "Tirupati",
  "Buchinaidu Kandriga": "Tirupati",
  "Chandragiri": "Tirupati",
  "Chilakuru": "Tirupati",
  "Chinnagottigallu": "Tirupati",
  "Chittamuru": "Tirupati",
  "Dakkili": "Tirupati",
  "Doravarisatramu": "Tirupati",
  "Gudur ": "Tirupati",
  "K.V.B.Puram": "Tirupati",
  "Kota": "Tirupati",
  "Nagalapuram": "Tirupati",
  "Naidupeta": "Tirupati",
  "Narayanavanam": "Tirupati",
  "Ojili": "Tirupati",
  "Pakala": "Tirupati",
  "Pellakuru": "Tirupati",
  "Pichatur": "Tirupati",
  "Puttur": "Tirupati",
  "Ramachandrapuram ": "Tirupati",
  "Renigunta": "Tirupati",
  "Satyavedu": "Tirupati",
  "Srikalahasti": "Tirupati",
  "Sullurpeta": "Tirupati",
  "Tada": "Tirupati",
  "Thottambedu": "Tirupati",
  "Tirupati (Rural)": "Tirupati",
  "Tirupati (Urban)": "Tirupati",
  "Vadamalapeta": "Tirupati",
  "Vakadu": "Tirupati",
  "Varadaiahpalem": "Tirupati",
  "Venkatagiri": "Tirupati",
  "Yerpedu": "Tirupati",
  "Yerravaripalem": "Tirupati",
  "Anandapuram": "Visakhapatnam",
  "Bheemunipatnam": "Visakhapatnam",
  "Gajuwaka": "Visakhapatnam",
  "Gopalapatnam": "Visakhapatnam",
  "Maharanipeta": "Visakhapatnam",
  "Mulagada": "Visakhapatnam",
  "Padmanabham": "Visakhapatnam",
  "Pedagantyada": "Visakhapatnam",
  "Pendurthi": "Visakhapatnam",
  "Seethammadhara": "Visakhapatnam",
  "Visakhapatnam (rural)": "Visakhapatnam",
  "Badangi": "Vizianagaram",
  "Bhogapuram": "Vizianagaram",
  "Bobbili": "Vizianagaram",
  "Bondapalle": "Vizianagaram",
  "Cheepurupalle": "Vizianagaram",
  "Dattirajeru": "Vizianagaram",
  "Denkada": "Vizianagaram",
  "Gajapathinagaram": "Vizianagaram",
  "Gantyada": "Vizianagaram",
  "Garividi": "Vizianagaram",
  "Gurla": "Vizianagaram",
  "Jami": "Vizianagaram",
  "Kothavalasa": "Vizianagaram",
  "Lakkavarapukota": "Vizianagaram",
  "Mentada": "Vizianagaram",
  "Merakamudidam": "Vizianagaram",
  "Nellimarla": "Vizianagaram",
  "Pusapatirega": "Vizianagaram",
  "Rajam": "Vizianagaram",
  "Ramabhadrapuram": "Vizianagaram",
  "Regidi Amadalavalasa": "Vizianagaram",
  "Santhakaviti": "Vizianagaram",
  "Srungavarapukota": "Vizianagaram",
  "Therlam": "Vizianagaram",
  "Vangara": "Vizianagaram",
  "Vepada": "Vizianagaram",
  "Vizianagaram": "Vizianagaram",
  "Achanta": "West Godavari",
  "Akividu": "West Godavari",
  "Attili": "West Godavari",
  "Bhimavaram": "West Godavari",
  "Iragavaram": "West Godavari",
  "Kalla": "West Godavari",
  "Mogalthur": "West Godavari",
  "Palacoderu": "West Godavari",
  "Palakollu": "West Godavari",
  "Pentapadu": "West Godavari",
  "Penugonda": "West Godavari",
  "Penumantra": "West Godavari",
  "Poduru": "West Godavari",
  "T.Narasapuram": "West Godavari",
  "Tadepalligudem": "West Godavari",
  "Tanuku": "West Godavari",
  "Undi": "West Godavari",
  "Veeravasaram": "West Godavari",
  "Yelamanchili ": "West Godavari",
  "Atlur": "YSR Kadapa",
  "B.Kodur": "YSR Kadapa",
  "Badvel": "YSR Kadapa",
  "Brahmamgarimattam": "YSR Kadapa",
  "Chakrayapet": "YSR Kadapa",
  "Chapad": "YSR Kadapa",
  "Chennur": "YSR Kadapa",
  "Chinthakommadinne": "YSR Kadapa",
  "Duvvur": "YSR Kadapa",
  "Gopavaram": "YSR Kadapa",
  "Jammalamadugu": "YSR Kadapa",
  "Kadapa": "YSR Kadapa",
  "Kalasapadu": "YSR Kadapa",
  "Kamalapuram": "YSR Kadapa",
  "Khajipet": "YSR Kadapa",
  "Kondapuram ": "YSR Kadapa",
  "Lingala": "YSR Kadapa",
  "Muddanur": "YSR Kadapa",
  "Mylavaram ": "YSR Kadapa",
  "Peddamudium": "YSR Kadapa",
  "Pendlimarri": "YSR Kadapa",
  "Porumamilla": "YSR Kadapa",
  "Proddatur": "YSR Kadapa",
  "Pulivendla": "YSR Kadapa",
  "Rajupalem ": "YSR Kadapa",
  "S.Mydukur": "YSR Kadapa",
  "Sidhout": "YSR Kadapa",
  "Simhadripuram": "YSR Kadapa",
  "Sri Avadhutha Kasinayana": "YSR Kadapa",
  "Thondur": "YSR Kadapa",
  "Vallur": "YSR Kadapa",
  "Veerapunayunipalle": "YSR Kadapa",
  "Vempalle": "YSR Kadapa",
  "Vemula": "YSR Kadapa",
  "Vontimitta": "YSR Kadapa",
  "Yerraguntla": "YSR Kadapa",
};

var revenueVillages = {
  "Araveedu": "Galiveedu",
  "Eguvagottiveedu": "Galiveedu",
  "Galiveedu": "Galiveedu",
  "Garugupalle": "Galiveedu",
  "Gopanapalle": "Galiveedu",
  "Gundlacheruvu": "Galiveedu",
  "Korlakunta": "Galiveedu",
  "Nooliveedu": "Galiveedu",
  "Pandikunta": "Galiveedu",
  "Pulikunta": "Galiveedu",
  "Pyarampalle": "Galiveedu",
  "Talamudipi": "Galiveedu",
  "Thumukunta": "Galiveedu",
  "Veligallu": "Galiveedu",
  "Ananthapuram": "Lakkireddipalle",
  "Brahmana Yerragudi": "Lakkireddipalle",
  "Dappepalle": "Lakkireddipalle",
  "Dinnepadu": "Lakkireddipalle",
  "Gudlavaripalle": "Lakkireddipalle",
  "Kakulavaram": "Lakkireddipalle",
  "Kurnoothala": "Lakkireddipalle",
  "Lakkireddypalle": "Lakkireddipalle",
  "Maddirevula": "Lakkireddipalle",
  "Naraharibatlapalle": "Lakkireddipalle",
  "Pandillapalle": "Lakkireddipalle",
  "Somabatlapalle": "Lakkireddipalle",
  "Bandlapalle": "Ramapuram",
  "Chitlur": "Ramapuram",
  "Gopagudipalle": "Ramapuram",
  "Guvvalacheruvu": "Ramapuram",
  "Hasanapuram": "Ramapuram",
  "Kalpanayunicheruvu": "Ramapuram",
  "Nallaguttapalle": "Ramapuram",
  "Neelakantaraopeta": "Ramapuram",
  "Pothukurupalle": "Ramapuram",
  "Rachapalle": "Ramapuram",
  "Saraswathipalle": "Ramapuram",
  "Suddamalla": "Ramapuram",
};

var habitations = {
  "Appakondaiahgaripalle": "Lakkireddypalle",
  "Chintakuntavandlapalle": "Lakkireddypalle",
  "Dakshinamitta Harijanawada": "Lakkireddypalle",
  "Gandlapalle": "Lakkireddypalle",
  "Ganganapalle": "Lakkireddypalle",
  "Lakkireddypalle": "Lakkireddypalle",
  "Malapalli": "Lakkireddypalle",
  "Nandivandlapalle": "Lakkireddypalle",
  "Reddyvaripalle": "Lakkireddypalle",
  "Uttaramitta Harijanawada": "Lakkireddypalle",
  "Appalarajugaripalle": "Maddirevula",
  "Batamadigapalle": "Maddirevula",
  "Budidhaguntapalle": "Maddirevula",
  "Edigapalle": "Maddirevula",
  "G.M.R. Colony": "Maddirevula",
  "Nehrunagar": "Maddirevula",
  "Chagalaguttapalle": "Kurnoothala",
  "Devalampalle": "Kurnoothala",
  "Diguva Battinavandlapalle": "Kurnoothala",
  "Eguva Battinavandlapalle": "Kurnoothala",
  "Gandhamvaripalle": "Kurnoothala",
  "Guravaiahgaripalle": "Kurnoothala",
  "Kasthurirajugaripalle": "Kurnoothala",
  "Madigapalle": "Kurnoothala",
  "Malapalli ": "Kurnoothala",
  "Siddakavandlapalle": "Kurnoothala",

  "Chenikkayalapalli": "Chitlur",
};
